### ISSUE TITLE
keybindings cheatsheet?

### ISSUE THREAD

**Issue by Ramiferous** [jcs/sdorfehs#11]
Hey mate, just wondering if you're able to wip up a keybindings cheatsheet for the uninitiated? Not everything is crystal clear in the `config.h` file.
Specifically, what is the default keybinding to open `xterm`?

**Comment by jcs** [comment]
`Control+a`, then `c` will run `xterm`.

You can do `Control+a`, then `?` to see all of the bindings.

**Comment by Ramiferous** [comment]
Didn't want to open a new issue, but wanted to know: Is there a way to make a frame 'fullscreen' thereby eliminating and gaps set in config?

**Comment by jcs** [comment]
`set onlyborder 0` to eliminate gaps/borders when there is only one frame.

Also useful is `Control+a` then `Q` which will run the `only` command, which removes all frames except the current one.  `Control+a` then `u` will undo that and restore the previous configuration.

**Comment by Ramiferous** [comment]
Ahhh sweet, that's what I'm after. I'm really enjoying it, I think I'll stick with it full time. Cheers! :)
