### ISSUE TITLE
[feature request] Toggle bar & move bar to bottom

### ISSUE THREAD

**Issue by Ramiferous** [jcs/sdorfehs#15]
Hi again. I've been using `sdorfehs` for nearly 6 months and I'm very comfortable in it. 
Some things I wish I could do however:

1. Toggle the bar
2. Relocate the bar to the bottom

Unfortunately I'm not skilled enough to try and write a patch to send you as a PR, and I understand if you have no interest in adding these features, I just though Id ask :)

Cheers

**Comment by jcs** [comment]
`set barsticky 0`

`set bargravity sw`

**Comment by Ramiferous** [comment]
> 
> 
> `set barsticky 0`
> 
> `set bargravity sw`

Toggle show/hide?

**Comment by jcs** [comment]
`set barsticky 0` will hide the bar, `set barsticky 1` will show it.  If you want to toggle it from a key binding, you would need to call out to a shell script:

```
#!/bin/sh

STICKY=`sdorfehs -c "set barsticky"`

if [ "$STICKY" = "1" ]; then
    STICKY=0
else
    STICKY=1
fi

sdorfehs -c "set barsticky ${STICKY}"
```

**Comment by Ramiferous** [comment]
Thanks, works like a charm!
