### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by throwaway1611** [jcs/sdorfehs#20]
Would it be possible to enable two escape keys? I would like to be able to use the windows key and menu key on a Thinkpad 420 as the mod/escape. If this is already available I apologize, I couldn't find it in the documentation. Thank you so much.

**Comment by jcs** [comment]
Do you mean either key acts as the escape or that you want both keys to have to be pressed to enter escape mode?

**Comment by throwaway1611** [comment]
Either key for less hand movement.

**Comment by jcs** [comment]
Do you need the other key for anything else?  If not, you could just make both of them generate the same keysym with `xmodmap`.

**Comment by throwaway1611** [comment]
How would you do this? Everytime I time to map them same it disables one or the other?

**Comment by throwaway1611** [comment]
I'm using your most current snap, and OpenBSD 7.0 -current
