### ISSUE TITLE
vmove & bar color

### ISSUE THREAD

**Issue by pfr-dev** [jcs/sdorfehs#22]
`"Windows can be moved between virtual screens with vmove"`

How to I set the key binding for `vmove`? I cant seem to figure it out. 

Second question, 

Is it not possible to set the bar and bar font color? I have `set barcolor #444444` in my config file but it does not appear to set the bar's color.

Cheers,

**Comment by DN-debug** [comment]
To answer your first question, I'm using the below bindings ( much like Ratpoison, you just have to **definekey** to make it work without pressing the 'modifier' ): 

#### swap workspaces
definekey top M-1 vselect 0
definekey top M-2 vselect 1
definekey top M-3 vselect 2
definekey top M-4 vselect 3

#### move current window to another workspace
definekey top C-1  vmove 0
definekey top C-2  vmove 1
definekey top C-3  vmove 2
definekey top C-4  vmove 3

You may change the keys the way you want..

And honestly idk the direct answer to your second question, but if you have used dzen2, then Sdorfehs bar supports some of its format and you can just pipe the output with a bg and fg into the ~/.config/sdorfehs/bar .

**Comment by jcs** [comment]
The bar uses the `fgcolor` value for text by default, but your bar text can have any color with `^fg(blue)this is blue text^fg()`
