### ISSUE TITLE
`sdorfehs -c "set barsticky 0"` breaks wm functionality

### ISSUE THREAD

**Issue by pfr-dev** [jcs/sdorfehs#24]
Starting a separate issue for this. If a picture speaks 1000 words then a video must speak more. Please watch this clip and see the video description for details.

https://youtu.be/VfZ0jppeNaE

If however you require a detailed written description let know and I'll type one out.

**Comment by pfr-dev** [comment]
I looked as though this [latest commit](https://github.com/jcs/sdorfehs/commit/f64fd9900fa9b95d337135a60bbf34ea74c42ede) may be addressing this issue?

**Comment by jcs** [comment]
@pfr-dev Can you reproduce this with 80bd8a8?

**Comment by pfr-dev** [comment]
Hey, I'll give this a try as soon as possible and let you know. Hopefully in there next couple of days.

**Comment by pfr-dev** [comment]
@jcs I've tested your changed and sadly it produces the same unwanted behavior as before.

**Comment by jcs** [comment]
Ok I can reproduce this now.  I think there are two separate issues:

1. After setting 'barsticky 0', the bar is not hidden.  If you `C-a Tab` or do something to change the contents of the bar, the bar will hide.
2. After resizing the screen by making the bar unsticky, the top terminal frames adjust their `y` value to the new screen top, but the frame in the top right does not have its `height` adjusted so it produces a big gap between it and the one below it.

**Comment by pfr-dev** [comment]
Will test asap and report back. Within 24 hours hopefully.

**Comment by pfr-dev** [comment]
**The good news:**  

The functionality has returned and the bar toggle script does succeed in toggling the bar

**The bad news:**

There is a significant delay when toggling the bar off `sdorfehs -c "set barsticky 0"`. I'd say about a 4 second delay.  There is no delay bringing the bar back with `sdorfehs -c "set barsticky 1"`

**Comment by pfr-dev** [comment]
Yep. That did the trick. :+1: 

Can we get a new release tag please :pray: 

I think we can probably close this issue now. Cheers
