### ISSUE TITLE
can't rotate with `next` through windows in different physical screens (same vscreen)

### ISSUE THREAD

**Issue by kidd** [jcs/sdorfehs#25]
Long time ratpoison user here, just trying to move to sdorfehs now. Thanks for keeping rp alive in some form :)

Maybe this is a feature and not a bug, but I'd like to make sure those changes are intentional.

In ratpoison, different physical screens share the 'group', so no matter in which physical screen you created each window, everything is reachable from both screens.  Also, switching the active group (workspace), both screens change the group. 

In sdorfehs, different physical screens act as totally different 'namespaces'. the `sdorfehs -c windows` lists are independent.  
Also (related but not the same bug) changing vscreen on one physical screen, doesn't change the vscreen in the other, creating a weird dettatchment of vscreens, screens and windows.   (I can have physical-screen-1 in vscreen1-screen1  and physical-screen-2 showing vscreen2-screen2)

Is this the intended behavior? IMHO it makes things a bit confusing, as the possible "configurations" gets very big.

I can provide more concrete examples if my explanations are not clear enough.

**Comment by kidd** [comment]
Oh, I see this issue is discussed in https://github.com/jcs/sdorfehs/issues/17 ... In my workflow, I don't want to jail windows to physical windows, but have everything available from everywhere.  

Seeing it's a deliberate decision to make it work as it is, I'll give it a few days, and if I can't get used to it, I guess I'll move back to rp :/

**Comment by jcs** [comment]
This is the current behavior by design
