### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by danielwwk** [jcs/sdorfehs#26]
OS: Archlinux
$ make
cc -O2 -Wall -Wunused -Wmissing-prototypes -Wstrict-prototypes -Wunused -DSYSCONFDIR="\"/etc\"" `pkg-config --cflags x11 xft xrandr xtst`   -c -o actions.o actions.c
In file included from sdorfehs.h:88,
                 from actions.c:33:
util.h:20:7: error: expected ‘;’ before ‘void’
   20 | __dead void fatal(const char *msg);
      |       ^~~~~
      |       ;
make: *** [<builtin>: actions.o] Error 1

**Comment by jcs** [comment]
Which C compiler/version is that?

**Comment by danielwwk** [comment]
cc (GCC) 11.2.0
Archlinux 5.17.4-arch1-1

Thanks

**Comment by jcs** [comment]
Can you try compiling with this:

```
diff --git util.h util.h
index f5806b1..b376b0c 100644
--- util.h
+++ util.h
@@ -17,6 +17,10 @@
 #ifndef UTIL_H
 #define UTIL_H
 
+#ifndef __dead
+#define __dead	__attribute__((__noreturn__))
+#endif
+
 __dead void fatal(const char *msg);
 void *xmalloc(size_t size);
 void *xrealloc(void *ptr, size_t size);
````

**Comment by danielwwk** [comment]
Ok, Thanks.
