### ISSUE TITLE
Incorrect frame number display (key press C-a Frame#)

### ISSUE THREAD

**Issue by danielwwk** [jcs/sdorfehs#27]
reproduce steps:

C-a c; Press key Ctrl - a c
C-a ! firefox
C-a ! emacs
C-a S
C-a s

C-a w; show windows list as below:
0-xterm
1+firefox
2-emacs

C-a 0 ; show incorrect frame number e.g. "Frame 2"
C-a 1; show correct frame number e.g. "Frame 1"
C-a 2; show incorrect frame number e.g."Frame 0"
selected frame location is correct except prompted message

One monitor w/ resolution 1920x1080

**Comment by jcs** [comment]
`C-a 0` selects window 0, not frame 0.

You can see frames with `C-a f`, and then type a number to select that frame.

**Comment by danielwwk** [comment]
IC, Thanks.
