### ISSUE TITLE
`C-u` kills xserver

### ISSUE THREAD

**Issue by pfr-dev** [jcs/sdorfehs#31]
sdorfehs 1.3
NetBSD 9.2_STABLE

### Issue:
When using the keybinding `C-u` or `C-U` to _undo_ the previous action, the xserver is terminated. 

### How to replicate:

1. Start xserver with `startx`
2. Split the frames at least once so there is at least one action to undo
3. Attempt to undo the action with `C-u`
4. Get booted out of xserver back to your TTY

I'm not sure if anything in my `Xorg.0.log` has any hints, but I've attached it [here](http://ix.io/3XXu) for good measure.

**Comment by jcs** [comment]
Did you try this with a7c65942c85?

**Comment by pfr-dev** [comment]
Thanks. That surely does the trick. 
I tend not to build from git and rely on `pkgin` to update my packages. Unfortunately, this means that these commits/fixes aren't packaged until a new release is tagged. Can we possibly get `v1.3.1`?

**Comment by jcs** [comment]
I tagged v1.4
