### ISSUE TITLE
vmerge vdelete option? 

### ISSUE THREAD

**Issue by bazeeel** [jcs/sdorfehs#32]
Hi! 
How can i rename or delete vscreen name and add new?  Like in ratpoison groups gnewbg gmerge gdelete.

**Comment by jcs** [comment]
vscreens are fairly static, not like groups in ratpoison so there is no mechanism to delete, add, or merge vscreens.  You can rename one with `vrename` and adjust the number of them with `set vscreens`.

**Comment by bazeeel** [comment]
This is my problem...the default vscreen  
[https://ibb.co/L1rGZHv](url)
![pic-selected-220621-0626-37](https://user-images.githubusercontent.com/33565327/174716516-dba574dc-ad11-42ce-8445-c4a9937cfbe4.png)

**Comment by jcs** [comment]
`vselect 0`
`vrename 0`

**Comment by bazeeel** [comment]
Thank you! Now is ok..........
