### ISSUE TITLE
even with the bar not fixed, there is an additional margin at the top.

### ISSUE THREAD

**Issue by gutierri** [jcs/sdorfehs#8]
a problem that i detected after the last commits of the week, is that it doesn’t read the initial value of the settings and some changes are only applied right after splitting the frames.

I made a screencast here also to facilitate visualization of the behavior, in this I include the current settings for the `bar`.

![out-8](https://user-images.githubusercontent.com/1111356/87356444-76313c00-c538-11ea-84c2-d573277411c2.gif)

**Comment by jcs** [comment]
I can't seem to reproduce that with your config, is that the whole thing?  You have red borders but your config doesn't show any uncommened `set bwcolor`.

**Comment by gutierri** [comment]
my settings are here[1](I make a symbolic link to local sdorfehs).

the point is that even with barsticky 0, it adds a margin.  it only disappears after creating a split in a frame and returning as a single frame (c-a q).

[1] https://github.com/gutierri/dotfiles/blob/master/ratpoison/.config/ratpoison/ratpoisonrc (ref #7)

Em 13 de jul de 2020, à(s) 19:00, joshua stein <notifications@github.com> escreveu:
